events {}

http {
    upstream minharede {
        server app1:3000;
        server app2:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://minharede;
            proxy_set_header Host $host;
        }
    }
}